# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e0b254e1d3460d93b69d7c8f68c33ea91b992c92a1175d6750c25656dd01f4e431309101e6881090ee801f9cd8c6861b112a585c3b702b7d7f819ec375e18f59

test:
  secret_key_base: c9cef52a9b20b6d5a6df07c14279b967c147026c20d8b9ca9083baa9e4b221839b8d2ad868e5637c145e2bfdf504c4536c41a7346f1f41489c48f8309f51824c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
